[project]
name = "py-tool"
version = "0.0.0"
description = ""
authors = []
dependencies = [
    "jinja2>=3.1.3",
]
requires-python = ">= 3.8"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.0.1",
    "pytest-sugar>=1.0.0",
]
lock-with-sources = true

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
